### ISSUE TITLE
Parse error:

### ISSUE THREAD

**Issue by xmanhattan** [Hi-Folks/array#32]
I received this error using wampserver 3.2.8 with php 7.2.1
Parse error: syntax error, unexpected '|', expecting ';' or '{' in C:\wamp\www\stats\statistics-main\src\Stat.php on line 34
just thought you should know.

**Comment by roberto-butti** [comment]
Hi @xmanhattan  thank you for your feedback.
You are using PHP version 7.2.1.
The package according to the composer,json supports PHP 8.0, PHP 8.1.

Also, the test suite on Github actions tests all the code with PHP 8.0 and 8.1.
If you have a similar issue on wampserver but with PHP 8.0 or 8.1 let me know.

Thank you

Roberto
