### ISSUE TITLE
Add Pint as code style fixer

### ISSUE THREAD

**Issue by roberto-butti** [Hi-Folks/array#33]
Add Pint https://github.com/laravel/pint as code style fixer

In composer.json, replace the 
`"format": "vendor/bin/php-cs-fixer fix --allow-risky=yes"`
with
`"format": "vendor/bin/pint"`

**Comment by roberto-butti** [comment]
sure @tharun634 ! pick it if you want! thank you

**Comment by tharun634** [comment]
> sure @tharun634 ! pick it if you want! thank you

Thank you, I'll send out the PR once the fest is started

**Comment by tharun634** [comment]
- How about the config rules for Pint? 
- Should I take care of the Github Actions as well?
- Do I remove [.php-cs-fixer.dist.php](https://github.com/Hi-Folks/array/blob/main/.php-cs-fixer.dist.php)? or is there a way we can use this with Pint. (PS. not very experienced with Pint)

**Comment by roberto-butti** [comment]
Hi @tharun634 for introducing pint you should create the pint.json file in the root directory of the project.
The content should be:
```
{
    "preset": "psr12"
}
```
We could use the PSR12 as preset.
And yes, we should remove phpcsfixer (and the configuration file)
And adjust the GitHub actions for running pint like this doc: https://laravelmagazine.com/blog/run-laravel-pint-as-part-of-your-ci-pipeline-with-github-actions
If you are not pretty familiar with GH action, i could split this into a new issue (adjusting the githubaction)

**Comment by tharun634** [comment]
Thanks for the config.

> If you are not pretty familiar with GH action

That's not a problem, my expertise is in CI/CD 😅
