### ISSUE TITLE
Making the PHPStan Level 9 on the CI Tests

### ISSUE THREAD

**Issue by RoadSigns** [Hi-Folks/array#54]
This is a task to increasing the PHPStan level to 9 on the CI test.
Currently the level is left blank, we can increase this to level 9 and then resolve some of the issues.

This will help us improve the quality of the package but also allow us to catch bugs before they are merged into the main branch.

The rules can be found here:
https://phpstan.org/user-guide/rule-levels

**Comment by roberto-butti** [comment]
@RoadSigns  thank you for this.
Now we already have level 5 (executing  `composer run phpstan` ).
I agree with working on improving the level.

**Comment by RoadSigns** [comment]
@roberto-butti Hope you had a good holiday period!

I'll take a look at this shortly, I might slowly increment this in a branch until we are happy with the results. 👍

**Comment by roberto-butti** [comment]
Hi, @RoadSigns  thank you, I had some rest, and I'm ready for 2023 :) I hope your holiday period was great as well.

My suggestion is to create more than one PR. One PR for 1 level. Or for example, if one level requires too much work, I think it is fine to open more and smaller PR

**Comment by RoadSigns** [comment]
@roberto-butti Sure that sounds perfectly fine!

I'll create one for PHPStan level 6 this evening then!

**Comment by roberto-butti** [comment]
This is the current configuration for phpstan:
https://github.com/Hi-Folks/array/blob/main/phpstan.neon

And we have in the composer the launch script:
https://github.com/Hi-Folks/array/blob/1bcf48da891be9afee96b9db7a79b06e1b40818f/composer.json#L42

**Comment by RoadSigns** [comment]
I'll probably just end up controlling it via `phpstan.neon` so that way the pipeline and the local tests are always the same.

You can control the level from there
https://github.com/Hi-Folks/array/blob/main/phpstan.neon#L2

**Comment by roberto-butti** [comment]
Thanks to the PR #62  and @RoadSigns  , I'm going to close this issue.
