### ISSUE TITLE
Improve documentation for groupBy(), transform() and OrderBy()

### ISSUE THREAD

**Issue by roberto-butti** [Hi-Folks/array#57]
Improving documentation examples for Table methods:
- groupBy(): grouping data
- transform(): transforms a specific field with the provided function
- orderBy(): sorting data (ascending or descending)

Where to improve:
- [x] README.md file
- [x] doc/table.md file
- [x] examples/cheatsheet_table.php

**Comment by RoadSigns** [comment]
Happy to be assigned to this 👍

**Comment by roberto-butti** [comment]
Thank you @RoadSigns !
