### ISSUE TITLE
Add Arr method: copyWithin()

### ISSUE THREAD

**Issue by roberto-butti** [Hi-Folks/array#9]
## What
Add new method to Arr class, in src/Arr.php file

## Description
The copyWithin() method shallow copies part of an array to another location in the same array and returns it without modifying its length

See: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/copyWithin

## Checklist
- [ ] implement method
- [ ] write phpdoc for the function
- [ ] write test in tests/ArrTest.php
- [ ]  execute composer format
- [ ] execute composer test-coverage
- [ ] check if your method has full test coverage
- [ ] add method in changelog
- [ ] update doc/arr.md adding a use case of the new method
- [ ] update cheatsheet (examples/cheatsheet.php)

**Comment by RoadSigns** [comment]
Hi 👋 

I'll happily pick this one up!

**Comment by roberto-butti** [comment]
Hi @RoadSigns , sure! thank you. I assigned it to you.
Enjoy your Hacktoberfest

**Comment by roberto-butti** [comment]
Thank you @RoadSigns for the PR, merged #41
